# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eigen Method
email: info@eigenmethod.com.ua
description: EigenMethod — молодая компания специализирующаяся в разработке программных комплексов.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://eigenmethod.com"
url: "http://eigenmethod.ru"
#url: "http://31.131.21.120"
#url: "http://localhost:4000"
#twitter_username: eigen
#github_username:  eigen

# Build settings
markdown: kramdown
encoding: utf-8
# safe: false
# plugins_dir: ./_plugins

# Pagination settings
paginate: 5
paginate_path: "/blog/page:num"

# Plugins
gems: ["jekyll-multiple-languages", "jekyll-paginate"]

# Languages settings
languages: ['ru', 'en']

# Excludes
exclude: ["lib_requirements.txt", "README.md", "add_posts_instruction.md",
          "hosting_install_instruction.md", "Gemfile", "Gemfile.lock"]

