# frozen_string_literal: true
source "https://rubygems.org"

# gem "rails"
gem "jekyll", "3.1.2"
gem "jekyll-paginate", "1.1.0"
gem "jekyll-multiple-languages", "2.0.3"
# gem "jekyll-multiple-languages-plugin"
